### ISSUE TITLE
Simplify yaml devices schema

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/rosdump#2]
The yaml device list looks like this

```yaml
devices:
  list:
    - options:
        host: 10.60.58.1
    - options:
        host: 10.60.58.2
    - options:
        host: 10.60.99.1
```

Why have this options list? and the list key?

It could be simplified to be:

```yaml
devices:
  name: 10.60.58.1
  name: 10.60.58.2
  name: 10.60.99.1
```

which is cleaner IMO, and still open for extension/addition of new parameters.
